# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=256)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_rate', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.ImageField(default=0, upload_to='')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSaleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=512)),
                ('business_number', models.CharField(max_length=16)),
                ('contact_number', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
    ]
