# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('owner', '0002_auto_20171001_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Owner'),
            preserve_default=False,
        ),
    ]
