# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='business_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
