# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20171011_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.IntegerField(default=0),
        ),
    ]
