# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_shop_shop_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('shop', 'name')]),
        ),
    ]
