# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_auto_20171121_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordersalemenu',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
