# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20171122_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
